[Interface]
PrivateKey = 2N2o+MuRs1A/L8plYRrFJYF1PHo85bTVOdq44lgbjk0=
Address = 10.8.0.3/24
# DNS = 8.8.8.8
MTU = 1280

[Peer]
PublicKey = 3BfTq7/0aAr0dUGRsoTMSjVNbGu1iNPHOPxgMSeC1xs=
PresharedKey = 4hZ1OU7aR80fNzcp7vpXxbYGZvbpak9dTcpGPNdRbdo=
AllowedIPs = 10.8.0.0/24, 192.168.1.0/24
Endpoint = 122.175.198.98:51820
PersistentKeepalive = 25
